name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Validate Apache VirtualHost configuration
      run: |
        echo "🔍 Testing Apache VirtualHost configuration..."
        
        # Install Apache2 for configuration testing
        sudo apt-get update
        sudo apt-get install -y apache2
        
        # Copy our VirtualHost configuration
        sudo cp apache-vhost.conf /etc/apache2/sites-available/portfolio_anthony.conf
        
        # Enable required Apache modules
        sudo a2enmod rewrite
        sudo a2enmod headers
        
        # Test the configuration syntax
        sudo apache2ctl configtest
        
        if [ $? -eq 0 ]; then
          echo "✅ Apache configuration is valid!"
        else
          echo "❌ Apache configuration has errors!"
          exit 1
        fi
        
        # Test enabling the site
        sudo a2ensite portfolio_anthony.conf
        sudo apache2ctl configtest
        
        if [ $? -eq 0 ]; then
          echo "✅ VirtualHost site configuration is valid!"
        else
          echo "❌ VirtualHost site configuration has errors!"
          exit 1
        fi

    - name: Validate PHP configuration
      run: |
        echo "🔍 Testing PHP configuration..."
        
        # Add Ondrej's PHP repository for latest PHP versions
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get update
        
        # Install PHP 8.2 (stable version available in the repo)
        sudo apt-get install -y php8.2-cli
        
        # Test PHP configuration syntax
        php8.2 -t -c php.ini
        
        if [ $? -eq 0 ]; then
          echo "✅ PHP configuration is valid!"
        else
          echo "❌ PHP configuration has errors!"
          exit 1
        fi

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/portfolio_anthony:latest

    - name: Call Portainer Webhook
      run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}